### ISSUE TITLE
How do i get the function address

### ISSUE THREAD

**Issue by PRNDA** [Reloaded-Project/Reloaded.Hooks#10]
like this:

FunctionPtr<MyCustomDelegate> functionPtr = new FunctionPtr<MyCustomDelegate>(0x123456);

where is 0x123456 came from?

**Comment by Sewer56** [comment]
You generally get the function address by reverse engineering the target executable using an application like Ghidra.

**Comment by PRNDA** [comment]
> You generally get the function address by reverse engineering the target executable using an application like Ghidra.

Thank you very much.
