### ISSUE TITLE
License question regarding Native AOT

### ISSUE THREAD

**Issue by TechInterMezzo** [Reloaded-Project/Reloaded.Hooks#24]
Is it possible to use this library with Native AOT without making the resulting application open source?
If I understand it correctly LGPL makes only exceptions for dynamic linking but Native AOT is producing one executable by statically linking everything together.

**Comment by Sewer56** [comment]
Thanks for reaching out.

For LGPL, the rule of thumb is technically the following:

- You must provide your users with a way to replace the LGPL library with a version they've modified. 

In the native world, this means providing the object code for your application, along with scripts or instructions on how to relink it with a new version of the library; but with NativeAOT that isn't really an option right now.

That said, offering to do this relinking as a service is also a valid option that would probably work for you 

The intent here is to ensure that the user's right to modify the LGPL library is not impeded by your choice to link it statically.

**Comment by TechInterMezzo** [comment]
Thank you for the answer. I will look for another way at the moment but maybe NativeAOT will support that some day.
