### ISSUE TITLE
Is this compatible with Linux/macOS?

### ISSUE THREAD

**Issue by sanny-io** [Reloaded-Project/Reloaded.Hooks#8]
Another hooking library I've looked into was using .NET Standard, but only supported Windows. I can't find any mention of compatibility with this project. Does this work anywhere .NET 5 works?

Thanks in advance.

**Comment by Sewer56** [comment]
Not at the current moment in time.
Most of the code is portable, however 2 dependencies of `Reloaded.Hooks` support only Windows at the moment.

That is
- [Reloaded.Assembler](https://github.com/Reloaded-Project/Reloaded.Assembler), which is a wrapper for the FASM assembler. It would need to be re-packaged with prebuilt binaries for other OSes.
- [Reloaded.Memory.Buffers](https://github.com/Reloaded-Project/Reloaded.Memory.Buffers) relies on the Windows API for memory allocation and enumerating memory pages. The former would be easy to replace but the latter might prove interesting.

In a supposed world where both supported Linux/OSX, this library would probably run under these platforms no problem.

**Comment by sanny-io** [comment]
I see. Appreciate the response 👍
